# -*- coding: utf-8 -*-
# Copyright (c) 2018-2020, libracore (https://www.libracore.com) and contributors
# For license information, please see license.txt
#
#
# This is a codelist resolver for EN16931
#
# Refer to unece.org/uncefact/codelistrecs.html
#

# refer to UNCL 6411
def get_unit_code(uom):
    if uom=='group': return '10'
    if uom=='outfit': return '11'
    if uom=='ration': return '13'
    if uom=='shot': return '14'
    if uom=='stick, military': return '15'
    if uom=='twenty foot container': return '20'
    if uom=='forty foot container': return '21'
    if uom=='decilitre per gram': return '22'
    if uom=='gram per cubic centimetre': return '23'
    if uom=='theoretical pound': return '24'
    if uom=='gram per square centimetre': return '25'
    if uom=='theoretical ton': return '27'
    if uom=='kilogram per square metre': return '28'
    if uom=='kilopascal square metre per gram': return '33'
    if uom=='kilopascal per millimetre': return '34'
    if uom=='millilitre per square centimetre second': return '35'
    if uom=='ounce per square foot': return '37'
    if uom=='ounce per square foot per 0,01inch': return '38'
    if uom=='millilitre per second': return '40'
    if uom=='millilitre per minute': return '41'
    if uom=='sitas': return '56'
    if uom=='mesh': return '57'
    if uom=='net kilogram': return '58'
    if uom=='part per million': return '59'
    if uom=='percent weight': return '60'
    if uom=='part per billion (US)': return '61'
    if uom=='millipascal': return '74'
    if uom=='milli-inch': return '77'
    if uom=='pound per square inch absolute': return '80'
    if uom=='henry': return '81'
    if uom=='foot pound-force': return '85'
    if uom=='pound per cubic foot': return '87'
    if uom=='poise': return '89'
    if uom=='stokes': return '91'
    if uom=='fixed rate': return '1I'
    if uom=='radian per second': return '2A'
    if uom=='radian per second squared': return '2B'
    if uom=='roentgen': return '2C'
    if uom=='volt AC': return '2G'
    if uom=='volt DC': return '2H'
    if uom=='British thermal unit (international table) per hour': return '2I'
    if uom=='cubic centimetre per second': return '2J'
    if uom=='cubic foot per hour': return '2K'
    if uom=='cubic foot per minute': return '2L'
    if uom=='centimetre per second': return '2M'
    if uom=='decibel': return '2N'
    if uom=='kilobyte': return '2P'
    if uom=='kilobecquerel': return '2Q'
    if uom=='kilocurie': return '2R'
    if uom=='megagram': return '2U'
    if uom=='metre per minute': return '2X'
    if uom=='milliroentgen': return '2Y'
    if uom=='millivolt': return '2Z'
    if uom=='megajoule': return '3B'
    if uom=='manmonth': return '3C'
    if uom=='centistokes': return '4C'
    if uom=='microlitre': return '4G'
    if uom=='micrometre (micron)': return '4H'
    if uom=='milliampere': return '4K'
    if uom=='megabyte': return '4L'
    if uom=='milligram per hour': return '4M'
    if uom=='megabecquerel': return '4N'
    if uom=='microfarad': return '4O'
    if uom=='newton per metre': return '4P'
    if uom=='ounce inch': return '4Q'
    if uom=='ounce foot': return '4R'
    if uom=='picofarad': return '4T'
    if uom=='pound per hour': return '4U'
    if uom=='ton (US) per hour': return '4W'
    if uom=='kilolitre per hour': return '4X'
    if uom=='barrel (US) per minute': return '5A'
    if uom=='batch': return '5B'
    if uom=='MMSCF/day': return '5E'
    if uom=='hydraulic horse power': return '5J'
    if uom=='ampere square metre per joule second': return 'A10'
    if uom=='angstrom': return 'A11'
    if uom=='astronomical unit': return 'A12'
    if uom=='attojoule': return 'A13'
    if uom=='barn': return 'A14'
    if uom=='barn per electronvolt': return 'A15'
    if uom=='barn per steradian electronvolt': return 'A16'
    if uom=='barn per steradian': return 'A17'
    if uom=='becquerel per kilogram': return 'A18'
    if uom=='becquerel per cubic metre': return 'A19'
    if uom=='ampere per centimetre': return 'A2'
    if uom=='British thermal unit (international table) per second square foot degree Rankine': return 'A20'
    if uom=='British thermal unit (international table) per pound degree Rankine': return 'A21'
    if uom=='British thermal unit (international table) per second foot degree Rankine': return 'A22'
    if uom=='British thermal unit (international table) per hour square foot degree Rankine': return 'A23'
    if uom=='candela per square metre': return 'A24'
    if uom=='coulomb metre': return 'A26'
    if uom=='coulomb metre squared per volt': return 'A27'
    if uom=='coulomb per cubic centimetre': return 'A28'
    if uom=='coulomb per cubic metre': return 'A29'
    if uom=='ampere per millimetre': return 'A3'
    if uom=='coulomb per cubic millimetre': return 'A30'
    if uom=='coulomb per kilogram second': return 'A31'
    if uom=='coulomb per mole': return 'A32'
    if uom=='coulomb per square centimetre': return 'A33'
    if uom=='coulomb per square metre': return 'A34'
    if uom=='coulomb per square millimetre': return 'A35'
    if uom=='cubic centimetre per mole': return 'A36'
    if uom=='cubic decimetre per mole': return 'A37'
    if uom=='cubic metre per coulomb': return 'A38'
    if uom=='cubic metre per kilogram': return 'A39'
    if uom=='ampere per square centimetre': return 'A4'
    if uom=='cubic metre per mole': return 'A40'
    if uom=='ampere per square metre': return 'A41'
    if uom=='curie per kilogram': return 'A42'
    if uom=='deadweight tonnage': return 'A43'
    if uom=='decalitre': return 'A44'
    if uom=='decametre': return 'A45'
    if uom=='decitex': return 'A47'
    if uom=='degree Rankine': return 'A48'
    if uom=='denier': return 'A49'
    if uom=='ampere square metre': return 'A5'
    if uom=='electronvolt': return 'A53'
    if uom=='electronvolt per metre': return 'A54'
    if uom=='electronvolt square metre': return 'A55'
    if uom=='electronvolt square metre per kilogram': return 'A56'
    if uom=='8-part cloud cover': return 'A59'
    if uom=='ampere per square metre kelvin squared': return 'A6'
    if uom=='exajoule': return 'A68'
    if uom=='farad per metre': return 'A69'
    if uom=='ampere per square millimetre': return 'A7'
    if uom=='femtojoule': return 'A70'
    if uom=='femtometre': return 'A71'
    if uom=='foot per second squared': return 'A73'
    if uom=='foot pound-force per second': return 'A74'
    if uom=='freight ton': return 'A75'
    if uom=='gal': return 'A76'
    if uom=='ampere second': return 'A8'
    if uom=='gigacoulomb per cubic metre': return 'A84'
    if uom=='gigaelectronvolt': return 'A85'
    if uom=='gigahertz': return 'A86'
    if uom=='gigaohm': return 'A87'
    if uom=='gigaohm metre': return 'A88'
    if uom=='gigapascal': return 'A89'
    if uom=='rate': return 'A9'
    if uom=='gigawatt': return 'A90'
    if uom=='gon': return 'A91'
    if uom=='gram per cubic metre': return 'A93'
    if uom=='gram per mole': return 'A94'
    if uom=='gray': return 'A95'
    if uom=='gray per second': return 'A96'
    if uom=='hectopascal': return 'A97'
    if uom=='henry per metre': return 'A98'
    if uom=='bit': return 'A99'
    if uom=='ball': return 'AA'
    if uom=='bulk pack': return 'AB'
    if uom=='acre': return 'ACR'
    if uom=='activity': return 'ACT'
    if uom=='byte': return 'AD'
    if uom=='ampere per metre': return 'AE'
    if uom=='additional minute': return 'AH'
    if uom=='average minute per call': return 'AI'
    if uom=='fathom': return 'AK'
    if uom=='access line': return 'AL'
    if uom=='ampere hour': return 'AMH'
    if uom=='ampere': return 'AMP'
    if uom=='year': return 'ANN'
    if uom=='troy ounce or apothecary ounce': return 'APZ'
    if uom=='anti-hemophilic factor (AHF) unit': return 'AQ'
    if uom=='assortment': return 'AS'
    if uom=='alcoholic strength by mass': return 'ASM'
    if uom=='alcoholic strength by volume': return 'ASU'
    if uom=='standard atmosphere': return 'ATM'
    if uom=='american wire gauge': return 'AWG'
    if uom=='assembly': return 'AY'
    if uom=='British thermal unit (international table) per pound': return 'AZ'
    if uom=='barrel (US) per day': return 'B1'
    if uom=='bit per second': return 'B10'
    if uom=='joule per kilogram kelvin': return 'B11'
    if uom=='joule per metre': return 'B12'
    if uom=='joule per square metre': return 'B13'
    if uom=='joule per metre to the fourth power': return 'B14'
    if uom=='joule per mole': return 'B15'
    if uom=='joule per mole kelvin': return 'B16'
    if uom=='credit': return 'B17'
    if uom=='joule second': return 'B18'
    if uom=='digit': return 'B19'
    if uom=='joule square metre per kilogram': return 'B20'
    if uom=='kelvin per watt': return 'B21'
    if uom=='kiloampere': return 'B22'
    if uom=='kiloampere per square metre': return 'B23'
    if uom=='kiloampere per metre': return 'B24'
    if uom=='kilobecquerel per kilogram': return 'B25'
    if uom=='kilocoulomb': return 'B26'
    if uom=='kilocoulomb per cubic metre': return 'B27'
    if uom=='kilocoulomb per square metre': return 'B28'
    if uom=='kiloelectronvolt': return 'B29'
    if uom=='batting pound': return 'B3'
    if uom=='gibibit': return 'B30'
    if uom=='kilogram metre per second': return 'B31'
    if uom=='kilogram metre squared': return 'B32'
    if uom=='kilogram metre squared per second': return 'B33'
    if uom=='kilogram per cubic decimetre': return 'B34'
    if uom=='kilogram per litre': return 'B35'
    if uom=='barrel, imperial': return 'B4'
    if uom=='kilojoule per kelvin': return 'B41'
    if uom=='kilojoule per kilogram': return 'B42'
    if uom=='kilojoule per kilogram kelvin': return 'B43'
    if uom=='kilojoule per mole': return 'B44'
    if uom=='kilomole': return 'B45'
    if uom=='kilomole per cubic metre': return 'B46'
    if uom=='kilonewton': return 'B47'
    if uom=='kilonewton metre': return 'B48'
    if uom=='kiloohm': return 'B49'
    if uom=='kiloohm metre': return 'B50'
    if uom=='kilosecond': return 'B52'
    if uom=='kilosiemens': return 'B53'
    if uom=='kilosiemens per metre': return 'B54'
    if uom=='kilovolt per metre': return 'B55'
    if uom=='kiloweber per metre': return 'B56'
    if uom=='light year': return 'B57'
    if uom=='litre per mole': return 'B58'
    if uom=='lumen hour': return 'B59'
    if uom=='lumen per square metre': return 'B60'
    if uom=='lumen per watt': return 'B61'
    if uom=='lumen second': return 'B62'
    if uom=='lux hour': return 'B63'
    if uom=='lux second': return 'B64'
    if uom=='megaampere per square metre': return 'B66'
    if uom=='megabecquerel per kilogram': return 'B67'
    if uom=='gigabit': return 'B68'
    if uom=='megacoulomb per cubic metre': return 'B69'
    if uom=='cycle': return 'B7'
    if uom=='megacoulomb per square metre': return 'B70'
    if uom=='megaelectronvolt': return 'B71'
    if uom=='megagram per cubic metre': return 'B72'
    if uom=='meganewton': return 'B73'
    if uom=='meganewton metre': return 'B74'
    if uom=='megaohm': return 'B75'
    if uom=='megaohm metre': return 'B76'
    if uom=='megasiemens per metre': return 'B77'
    if uom=='megavolt': return 'B78'
    if uom=='megavolt per metre': return 'B79'
    if uom=='joule per cubic metre': return 'B8'
    if uom=='gigabit per second': return 'B80'
    if uom=='reciprocal metre squared reciprocal second': return 'B81'
    if uom=='inch per linear foot': return 'B82'
    if uom=='metre to the fourth power': return 'B83'
    if uom=='microampere': return 'B84'
    if uom=='microbar': return 'B85'
    if uom=='microcoulomb': return 'B86'
    if uom=='microcoulomb per cubic metre': return 'B87'
    if uom=='microcoulomb per square metre': return 'B88'
    if uom=='microfarad per metre': return 'B89'
    if uom=='microhenry': return 'B90'
    if uom=='microhenry per metre': return 'B91'
    if uom=='micronewton': return 'B92'
    if uom=='micronewton metre': return 'B93'
    if uom=='microohm': return 'B94'
    if uom=='microohm metre': return 'B95'
    if uom=='micropascal': return 'B96'
    if uom=='microradian': return 'B97'
    if uom=='microsecond': return 'B98'
    if uom=='microsiemens': return 'B99'
    if uom=='bar [unit of pressure]': return 'BAR'
    if uom=='base box': return 'BB'
    if uom=='board foot': return 'BFT'
    if uom=='brake horse power': return 'BHP'
    if uom=='billion (EUR)': return 'BIL'
    if uom=='dry barrel (US)': return 'BLD'
    if uom=='barrel (US)': return 'BLL'
    if uom=='hundred board foot': return 'BP'
    if uom=='beats per minute': return 'BPM'
    if uom=='becquerel': return 'BQL'
    if uom=='British thermal unit (international table)': return 'BTU'
    if uom=='bushel (US)': return 'BUA'
    if uom=='bushel (UK)': return 'BUI'
    if uom=='call': return 'C0'
    if uom=='millifarad': return 'C10'
    if uom=='milligal': return 'C11'
    if uom=='milligram per metre': return 'C12'
    if uom=='milligray': return 'C13'
    if uom=='millihenry': return 'C14'
    if uom=='millijoule': return 'C15'
    if uom=='millimetre per second': return 'C16'
    if uom=='millimetre squared per second': return 'C17'
    if uom=='millimole': return 'C18'
    if uom=='mole per kilogram': return 'C19'
    if uom=='millinewton': return 'C20'
    if uom=='kibibit': return 'C21'
    if uom=='millinewton per metre': return 'C22'
    if uom=='milliohm metre': return 'C23'
    if uom=='millipascal second': return 'C24'
    if uom=='milliradian': return 'C25'
    if uom=='millisecond': return 'C26'
    if uom=='millisiemens': return 'C27'
    if uom=='millisievert': return 'C28'
    if uom=='millitesla': return 'C29'
    if uom=='microvolt per metre': return 'C3'
    if uom=='millivolt per metre': return 'C30'
    if uom=='milliwatt': return 'C31'
    if uom=='milliwatt per square metre': return 'C32'
    if uom=='milliweber': return 'C33'
    if uom=='mole': return 'C34'
    if uom=='mole per cubic decimetre': return 'C35'
    if uom=='mole per cubic metre': return 'C36'
    if uom=='kilobit': return 'C37'
    if uom=='mole per litre': return 'C38'
    if uom=='nanoampere': return 'C39'
    if uom=='nanocoulomb': return 'C40'
    if uom=='nanofarad': return 'C41'
    if uom=='nanofarad per metre': return 'C42'
    if uom=='nanohenry': return 'C43'
    if uom=='nanohenry per metre': return 'C44'
    if uom=='nanometre': return 'C45'
    if uom=='nanoohm metre': return 'C46'
    if uom=='nanosecond': return 'C47'
    if uom=='nanotesla': return 'C48'
    if uom=='nanowatt': return 'C49'
    if uom=='neper': return 'C50'
    if uom=='neper per second': return 'C51'
    if uom=='picometre': return 'C52'
    if uom=='newton metre second': return 'C53'
    if uom=='newton metre squared per kilogram squared': return 'C54'
    if uom=='newton per square metre': return 'C55'
    if uom=='newton per square millimetre': return 'C56'
    if uom=='newton second': return 'C57'
    if uom=='newton second per metre': return 'C58'
    if uom=='octave': return 'C59'
    if uom=='ohm centimetre': return 'C60'
    if uom=='ohm metre': return 'C61'
    if uom=='one': return 'C62'
    if uom=='parsec': return 'C63'
    if uom=='pascal per kelvin': return 'C64'
    if uom=='pascal second': return 'C65'
    if uom=='pascal second per cubic metre': return 'C66'
    if uom=='pascal second per metre': return 'C67'
    if uom=='petajoule': return 'C68'
    if uom=='phon': return 'C69'
    if uom=='centipoise': return 'C7'
    if uom=='picoampere': return 'C70'
    if uom=='picocoulomb': return 'C71'
    if uom=='picofarad per metre': return 'C72'
    if uom=='picohenry': return 'C73'
    if uom=='kilobit per second': return 'C74'
    if uom=='picowatt': return 'C75'
    if uom=='picowatt per square metre': return 'C76'
    if uom=='pound-force': return 'C78'
    if uom=='kilovolt ampere hour': return 'C79'
    if uom=='millicoulomb per kilogram': return 'C8'
    if uom=='rad': return 'C80'
    if uom=='radian': return 'C81'
    if uom=='radian square metre per mole': return 'C82'
    if uom=='radian square metre per kilogram': return 'C83'
    if uom=='radian per metre': return 'C84'
    if uom=='reciprocal angstrom': return 'C85'
    if uom=='reciprocal cubic metre': return 'C86'
    if uom=='reciprocal cubic metre per second': return 'C87'
    if uom=='reciprocal electron volt per cubic metre': return 'C88'
    if uom=='reciprocal henry': return 'C89'
    if uom=='coil group': return 'C9'
    if uom=='reciprocal joule per cubic metre': return 'C90'
    if uom=='reciprocal kelvin or kelvin to the power minus one': return 'C91'
    if uom=='reciprocal metre': return 'C92'
    if uom=='reciprocal square metre': return 'C93'
    if uom=='reciprocal minute': return 'C94'
    if uom=='reciprocal mole': return 'C95'
    if uom=='reciprocal pascal or pascal to the power minus one': return 'C96'
    if uom=='reciprocal second': return 'C97'
    if uom=='reciprocal second per metre squared': return 'C99'
    if uom=='carrying capacity in metric ton': return 'CCT'
    if uom=='candela': return 'CDL'
    if uom=='degree Celsius': return 'CEL'
    if uom=='hundred': return 'CEN'
    if uom=='card': return 'CG'
    if uom=='centigram': return 'CGM'
    if uom=='coulomb per kilogram': return 'CKG'
    if uom=='hundred leave': return 'CLF'
    if uom=='centilitre': return 'CLT'
    if uom=='square centimetre': return 'CMK'
    if uom=='cubic centimetre': return 'CMQ'
    if uom=='centimetre': return 'CMT'
    if uom=='hundred pack': return 'CNP'
    if uom=='cental (UK)': return 'CNT'
    if uom=='coulomb': return 'COU'
    if uom=='content gram': return 'CTG'
    if uom=='metric carat': return 'CTM'
    if uom=='content ton (metric)': return 'CTN'
    if uom=='curie': return 'CUR'
    if uom=='hundred pound (cwt) / hundred weight (US)': return 'CWA'
    if uom=='hundred weight (UK)': return 'CWI'
    if uom=='kilowatt hour per hour': return 'D03'
    if uom=='lot [unit of weight]': return 'D04'
    if uom=='reciprocal second per steradian': return 'D1'
    if uom=='siemens per metre': return 'D10'
    if uom=='mebibit': return 'D11'
    if uom=='siemens square metre per mole': return 'D12'
    if uom=='sievert': return 'D13'
    if uom=='sone': return 'D15'
    if uom=='square centimetre per erg': return 'D16'
    if uom=='square centimetre per steradian erg': return 'D17'
    if uom=='metre kelvin': return 'D18'
    if uom=='square metre kelvin per watt': return 'D19'
    if uom=='reciprocal second per steradian metre squared': return 'D2'
    if uom=='square metre per joule': return 'D20'
    if uom=='square metre per kilogram': return 'D21'
    if uom=='square metre per mole': return 'D22'
    if uom=='pen gram (protein)': return 'D23'
    if uom=='square metre per steradian': return 'D24'
    if uom=='square metre per steradian joule': return 'D25'
    if uom=='square metre per volt second': return 'D26'
    if uom=='steradian': return 'D27'
    if uom=='terahertz': return 'D29'
    if uom=='terajoule': return 'D30'
    if uom=='terawatt': return 'D31'
    if uom=='terawatt hour': return 'D32'
    if uom=='tesla': return 'D33'
    if uom=='tex': return 'D34'
    if uom=='megabit': return 'D36'
    if uom=='tonne per cubic metre': return 'D41'
    if uom=='tropical year': return 'D42'
    if uom=='unified atomic mass unit': return 'D43'
    if uom=='var': return 'D44'
    if uom=='volt squared per kelvin squared': return 'D45'
    if uom=='volt - ampere': return 'D46'
    if uom=='volt per centimetre': return 'D47'
    if uom=='volt per kelvin': return 'D48'
    if uom=='millivolt per kelvin': return 'D49'
    if uom=='kilogram per square centimetre': return 'D5'
    if uom=='volt per metre': return 'D50'
    if uom=='volt per millimetre': return 'D51'
    if uom=='watt per kelvin': return 'D52'
    if uom=='watt per metre kelvin': return 'D53'
    if uom=='watt per square metre': return 'D54'
    if uom=='watt per square metre kelvin': return 'D55'
    if uom=='watt per square metre kelvin to the fourth power': return 'D56'
    if uom=='watt per steradian': return 'D57'
    if uom=='watt per steradian square metre': return 'D58'
    if uom=='weber per metre': return 'D59'
    if uom=='roentgen per second': return 'D6'
    if uom=='weber per millimetre': return 'D60'
    if uom=='minute [unit of angle]': return 'D61'
    if uom=='second [unit of angle]': return 'D62'
    if uom=='book': return 'D63'
    if uom=='round': return 'D65'
    if uom=='number of words': return 'D68'
    if uom=='inch to the fourth power': return 'D69'
    if uom=='joule square metre': return 'D73'
    if uom=='kilogram per mole': return 'D74'
    if uom=='megacoulomb': return 'D77'
    if uom=='megajoule per second': return 'D78'
    if uom=='microwatt': return 'D80'
    if uom=='microtesla': return 'D81'
    if uom=='microvolt': return 'D82'
    if uom=='millinewton metre': return 'D83'
    if uom=='microwatt per square metre': return 'D85'
    if uom=='millicoulomb': return 'D86'
    if uom=='millimole per kilogram': return 'D87'
    if uom=='millicoulomb per cubic metre': return 'D88'
    if uom=='millicoulomb per square metre': return 'D89'
    if uom=='rem': return 'D91'
    if uom=='second per cubic metre': return 'D93'
    if uom=='second per cubic metre radian': return 'D94'
    if uom=='joule per gram': return 'D95'
    if uom=='decare': return 'DAA'
    if uom=='ten day': return 'DAD'
    if uom=='day': return 'DAY'
    if uom=='dry pound': return 'DB'
    if uom=='degree [unit of angle]': return 'DD'
    if uom=='decade': return 'DEC'
    if uom=='decigram': return 'DG'
    if uom=='decagram': return 'DJ'
    if uom=='decilitre': return 'DLT'
    if uom=='cubic decametre': return 'DMA'
    if uom=='square decimetre': return 'DMK'
    if uom=='standard kilolitre': return 'DMO'
    if uom=='cubic decimetre': return 'DMQ'
    if uom=='decimetre': return 'DMT'
    if uom=='decinewton metre': return 'DN'
    if uom=='dozen piece': return 'DPC'
    if uom=='dozen pair': return 'DPR'
    if uom=='displacement tonnage': return 'DPT'
    if uom=='dram (US)': return 'DRA'
    if uom=='dram (UK)': return 'DRI'
    if uom=='dozen roll': return 'DRL'
    if uom=='dry ton': return 'DT'
    if uom=='decitonne': return 'DTN'
    if uom=='pennyweight': return 'DWT'
    if uom=='dozen': return 'DZN'
    if uom=='dozen pack': return 'DZP'
    if uom=='newton per square centimetre': return 'E01'
    if uom=='megawatt hour per hour': return 'E07'
    if uom=='megawatt per hertz': return 'E08'
    if uom=='milliampere hour': return 'E09'
    if uom=='degree day': return 'E10'
    if uom=='mille': return 'E12'
    if uom=='kilocalorie (international table)': return 'E14'
    if uom=='kilocalorie (thermochemical) per hour': return 'E15'
    if uom=='million Btu(IT) per hour': return 'E16'
    if uom=='cubic foot per second': return 'E17'
    if uom=='tonne per hour': return 'E18'
    if uom=='ping': return 'E19'
    if uom=='megabit per second': return 'E20'
    if uom=='shares': return 'E21'
    if uom=='TEU': return 'E22'
    if uom=='tyre': return 'E23'
    if uom=='active unit': return 'E25'
    if uom=='dose': return 'E27'
    if uom=='air dry ton': return 'E28'
    if uom=='strand': return 'E30'
    if uom=='square metre per litre': return 'E31'
    if uom=='litre per hour': return 'E32'
    if uom=='foot per thousand': return 'E33'
    if uom=='gigabyte': return 'E34'
    if uom=='terabyte': return 'E35'
    if uom=='petabyte': return 'E36'
    if uom=='pixel': return 'E37'
    if uom=='megapixel': return 'E38'
    if uom=='dots per inch': return 'E39'
    if uom=='gross kilogram': return 'E4'
    if uom=='part per hundred thousand': return 'E40'
    if uom=='kilogram-force per square millimetre': return 'E41'
    if uom=='kilogram-force per square centimetre': return 'E42'
    if uom=='joule per square centimetre': return 'E43'
    if uom=='kilogram-force metre per square centimetre': return 'E44'
    if uom=='milliohm': return 'E45'
    if uom=='kilowatt hour per cubic metre': return 'E46'
    if uom=='kilowatt hour per kelvin': return 'E47'
    if uom=='service unit': return 'E48'
    if uom=='working day': return 'E49'
    if uom=='accounting unit': return 'E50'
    if uom=='job': return 'E51'
    if uom=='run foot': return 'E52'
    if uom=='test': return 'E53'
    if uom=='trip': return 'E54'
    if uom=='use': return 'E55'
    if uom=='well': return 'E56'
    if uom=='zone': return 'E57'
    if uom=='exabit per second': return 'E58'
    if uom=='exbibyte': return 'E59'
    if uom=='pebibyte': return 'E60'
    if uom=='tebibyte': return 'E61'
    if uom=='gibibyte': return 'E62'
    if uom=='mebibyte': return 'E63'
    if uom=='kibibyte': return 'E64'
    if uom=='exbibit per metre': return 'E65'
    if uom=='exbibit per square metre': return 'E66'
    if uom=='exbibit per cubic metre': return 'E67'
    if uom=='gigabyte per second': return 'E68'
    if uom=='gibibit per metre': return 'E69'
    if uom=='gibibit per square metre': return 'E70'
    if uom=='gibibit per cubic metre': return 'E71'
    if uom=='kibibit per metre': return 'E72'
    if uom=='kibibit per square metre': return 'E73'
    if uom=='kibibit per cubic metre': return 'E74'
    if uom=='mebibit per metre': return 'E75'
    if uom=='mebibit per square metre': return 'E76'
    if uom=='mebibit per cubic metre': return 'E77'
    if uom=='petabit': return 'E78'
    if uom=='petabit per second': return 'E79'
    if uom=='pebibit per metre': return 'E80'
    if uom=='pebibit per square metre': return 'E81'
    if uom=='pebibit per cubic metre': return 'E82'
    if uom=='terabit': return 'E83'
    if uom=='terabit per second': return 'E84'
    if uom=='tebibit per metre': return 'E85'
    if uom=='tebibit per cubic metre': return 'E86'
    if uom=='tebibit per square metre': return 'E87'
    if uom=='bit per metre': return 'E88'
    if uom=='bit per square metre': return 'E89'
    if uom=='reciprocal centimetre': return 'E90'
    if uom=='reciprocal day': return 'E91'
    if uom=='cubic decimetre per hour': return 'E92'
    if uom=='kilogram per hour': return 'E93'
    if uom=='kilomole per second': return 'E94'
    if uom=='mole per second': return 'E95'
    if uom=='degree per second': return 'E96'
    if uom=='millimetre per degree Celcius metre': return 'E97'
    if uom=='degree Celsius per kelvin': return 'E98'
    if uom=='hectopascal per bar': return 'E99'
    if uom=='each': return 'EA'
    if uom=='electronic mail box': return 'EB'
    if uom=='equivalent gallon': return 'EQ'
    if uom=='bit per cubic metre': return 'F01'
    if uom=='kelvin per kelvin': return 'F02'
    if uom=='kilopascal per bar': return 'F03'
    if uom=='millibar per bar': return 'F04'
    if uom=='megapascal per bar': return 'F05'
    if uom=='poise per bar': return 'F06'
    if uom=='pascal per bar': return 'F07'
    if uom=='milliampere per inch': return 'F08'
    if uom=='kelvin per hour': return 'F10'
    if uom=='kelvin per minute': return 'F11'
    if uom=='kelvin per second': return 'F12'
    if uom=='slug': return 'F13'
    if uom=='gram per kelvin': return 'F14'
    if uom=='kilogram per kelvin': return 'F15'
    if uom=='milligram per kelvin': return 'F16'
    if uom=='pound-force per foot': return 'F17'
    if uom=='kilogram square centimetre': return 'F18'
    if uom=='kilogram square millimetre': return 'F19'
    if uom=='pound inch squared': return 'F20'
    if uom=='pound-force inch': return 'F21'
    if uom=='pound-force foot per ampere': return 'F22'
    if uom=='gram per cubic decimetre': return 'F23'
    if uom=='kilogram per kilomol': return 'F24'
    if uom=='gram per hertz': return 'F25'
    if uom=='gram per day': return 'F26'
    if uom=='gram per hour': return 'F27'
    if uom=='gram per minute': return 'F28'
    if uom=='gram per second': return 'F29'
    if uom=='kilogram per day': return 'F30'
    if uom=='kilogram per minute': return 'F31'
    if uom=='milligram per day': return 'F32'
    if uom=='milligram per minute': return 'F33'
    if uom=='milligram per second': return 'F34'
    if uom=='gram per day kelvin': return 'F35'
    if uom=='gram per hour kelvin': return 'F36'
    if uom=='gram per minute kelvin': return 'F37'
    if uom=='gram per second kelvin': return 'F38'
    if uom=='kilogram per day kelvin': return 'F39'
    if uom=='kilogram per hour kelvin': return 'F40'
    if uom=='kilogram per minute kelvin': return 'F41'
    if uom=='kilogram per second kelvin': return 'F42'
    if uom=='milligram per day kelvin': return 'F43'
    if uom=='milligram per hour kelvin': return 'F44'
    if uom=='milligram per minute kelvin': return 'F45'
    if uom=='milligram per second kelvin': return 'F46'
    if uom=='newton per millimetre': return 'F47'
    if uom=='pound-force per inch': return 'F48'
    if uom=='rod [unit of distance]': return 'F49'
    if uom=='micrometre per kelvin': return 'F50'
    if uom=='centimetre per kelvin': return 'F51'
    if uom=='metre per kelvin': return 'F52'
    if uom=='millimetre per kelvin': return 'F53'
    if uom=='milliohm per metre': return 'F54'
    if uom=='ohm per mile (statute mile)': return 'F55'
    if uom=='ohm per kilometre': return 'F56'
    if uom=='milliampere per pound-force per square inch': return 'F57'
    if uom=='reciprocal bar': return 'F58'
    if uom=='milliampere per bar': return 'F59'
    if uom=='degree Celsius per bar': return 'F60'
    if uom=='kelvin per bar': return 'F61'
    if uom=='gram per day bar': return 'F62'
    if uom=='gram per hour bar': return 'F63'
    if uom=='gram per minute bar': return 'F64'
    if uom=='gram per second bar': return 'F65'
    if uom=='kilogram per day bar': return 'F66'
    if uom=='kilogram per hour bar': return 'F67'
    if uom=='kilogram per minute bar': return 'F68'
    if uom=='kilogram per second bar': return 'F69'
    if uom=='milligram per day bar': return 'F70'
    if uom=='milligram per hour bar': return 'F71'
    if uom=='milligram per minute bar': return 'F72'
    if uom=='milligram per second bar': return 'F73'
    if uom=='gram per bar': return 'F74'
    if uom=='milligram per bar': return 'F75'
    if uom=='milliampere per millimetre': return 'F76'
    if uom=='pascal second per kelvin': return 'F77'
    if uom=='inch of water': return 'F78'
    if uom=='inch of mercury': return 'F79'
    if uom=='water horse power': return 'F80'
    if uom=='bar per kelvin': return 'F81'
    if uom=='hectopascal per kelvin': return 'F82'
    if uom=='kilopascal per kelvin': return 'F83'
    if uom=='millibar per kelvin': return 'F84'
    if uom=='megapascal per kelvin': return 'F85'
    if uom=='poise per kelvin': return 'F86'
    if uom=='volt per litre minute': return 'F87'
    if uom=='newton centimetre': return 'F88'
    if uom=='newton metre per degree': return 'F89'
    if uom=='newton metre per ampere': return 'F90'
    if uom=='bar litre per second': return 'F91'
    if uom=='bar cubic metre per second': return 'F92'
    if uom=='hectopascal litre per second': return 'F93'
    if uom=='hectopascal cubic metre per second': return 'F94'
    if uom=='millibar litre per second': return 'F95'
    if uom=='millibar cubic metre per second': return 'F96'
    if uom=='megapascal litre per second': return 'F97'
    if uom=='megapascal cubic metre per second': return 'F98'
    if uom=='pascal litre per second': return 'F99'
    if uom=='degree Fahrenheit': return 'FAH'
    if uom=='farad': return 'FAR'
    if uom=='fibre metre': return 'FBM'
    if uom=='thousand cubic foot': return 'FC'
    if uom=='hundred cubic metre': return 'FF'
    if uom=='micromole': return 'FH'
    if uom=='failures in time': return 'FIT'
    if uom=='flake ton': return 'FL'
    if uom=='foot': return 'FOT'
    if uom=='pound per square foot': return 'FP'
    if uom=='foot per minute': return 'FR'
    if uom=='foot per second': return 'FS'
    if uom=='square foot': return 'FTK'
    if uom=='cubic foot': return 'FTQ'
    if uom=='pascal cubic metre per second': return 'G01'
    if uom=='centimetre per bar': return 'G04'
    if uom=='metre per bar': return 'G05'
    if uom=='millimetre per bar': return 'G06'
    if uom=='square inch per second': return 'G08'
    if uom=='square metre per second kelvin': return 'G09'
    if uom=='stokes per kelvin': return 'G10'
    if uom=='gram per cubic centimetre bar': return 'G11'
    if uom=='gram per cubic decimetre bar': return 'G12'
    if uom=='gram per litre bar': return 'G13'
    if uom=='gram per cubic metre bar': return 'G14'
    if uom=='gram per millilitre bar': return 'G15'
    if uom=='kilogram per cubic centimetre bar': return 'G16'
    if uom=='kilogram per litre bar': return 'G17'
    if uom=='kilogram per cubic metre bar': return 'G18'
    if uom=='newton metre per kilogram': return 'G19'
    if uom=='US gallon per minute': return 'G2'
    if uom=='pound-force foot per pound': return 'G20'
    if uom=='cup [unit of volume]': return 'G21'
    if uom=='peck': return 'G23'
    if uom=='tablespoon (US)': return 'G24'
    if uom=='teaspoon (US)': return 'G25'
    if uom=='stere': return 'G26'
    if uom=='cubic centimetre per kelvin': return 'G27'
    if uom=='litre per kelvin': return 'G28'
    if uom=='cubic metre per kelvin': return 'G29'
    if uom=='Imperial gallon per minute': return 'G3'
    if uom=='millilitre per kelvin': return 'G30'
    if uom=='kilogram per cubic centimetre': return 'G31'
    if uom=='ounce (avoirdupois) per cubic yard': return 'G32'
    if uom=='gram per cubic centimetre kelvin': return 'G33'
    if uom=='gram per cubic decimetre kelvin': return 'G34'
    if uom=='gram per litre kelvin': return 'G35'
    if uom=='gram per cubic metre kelvin': return 'G36'
    if uom=='gram per millilitre kelvin': return 'G37'
    if uom=='kilogram per cubic centimetre kelvin': return 'G38'
    if uom=='kilogram per litre kelvin': return 'G39'
    if uom=='kilogram per cubic metre kelvin': return 'G40'
    if uom=='square metre per second bar': return 'G41'
    if uom=='microsiemens per centimetre': return 'G42'
    if uom=='microsiemens per metre': return 'G43'
    if uom=='nanosiemens per centimetre': return 'G44'
    if uom=='nanosiemens per metre': return 'G45'
    if uom=='stokes per bar': return 'G46'
    if uom=='cubic centimetre per day': return 'G47'
    if uom=='cubic centimetre per hour': return 'G48'
    if uom=='cubic centimetre per minute': return 'G49'
    if uom=='gallon (US) per hour': return 'G50'
    if uom=='litre per second': return 'G51'
    if uom=='cubic metre per day': return 'G52'
    if uom=='cubic metre per minute': return 'G53'
    if uom=='millilitre per day': return 'G54'
    if uom=='millilitre per hour': return 'G55'
    if uom=='cubic inch per hour': return 'G56'
    if uom=='cubic inch per minute': return 'G57'
    if uom=='cubic inch per second': return 'G58'
    if uom=='milliampere per litre minute': return 'G59'
    if uom=='volt per bar': return 'G60'
    if uom=='cubic centimetre per day kelvin': return 'G61'
    if uom=='cubic centimetre per hour kelvin': return 'G62'
    if uom=='cubic centimetre per minute kelvin': return 'G63'
    if uom=='cubic centimetre per second kelvin': return 'G64'
    if uom=='litre per day kelvin': return 'G65'
    if uom=='litre per hour kelvin': return 'G66'
    if uom=='litre per minute kelvin': return 'G67'
    if uom=='litre per second kelvin': return 'G68'
    if uom=='cubic metre per day kelvin': return 'G69'
    if uom=='cubic metre per hour kelvin': return 'G70'
    if uom=='cubic metre per minute kelvin': return 'G71'
    if uom=='cubic metre per second kelvin': return 'G72'
    if uom=='millilitre per day kelvin': return 'G73'
    if uom=='millilitre per hour kelvin': return 'G74'
    if uom=='millilitre per minute kelvin': return 'G75'
    if uom=='millilitre per second kelvin': return 'G76'
    if uom=='millimetre to the fourth power': return 'G77'
    if uom=='cubic centimetre per day bar': return 'G78'
    if uom=='cubic centimetre per hour bar': return 'G79'
    if uom=='cubic centimetre per minute bar': return 'G80'
    if uom=='cubic centimetre per second bar': return 'G81'
    if uom=='litre per day bar': return 'G82'
    if uom=='litre per hour bar': return 'G83'
    if uom=='litre per minute bar': return 'G84'
    if uom=='litre per second bar': return 'G85'
    if uom=='cubic metre per day bar': return 'G86'
    if uom=='cubic metre per hour bar': return 'G87'
    if uom=='cubic metre per minute bar': return 'G88'
    if uom=='cubic metre per second bar': return 'G89'
    if uom=='millilitre per day bar': return 'G90'
    if uom=='millilitre per hour bar': return 'G91'
    if uom=='millilitre per minute bar': return 'G92'
    if uom=='millilitre per second bar': return 'G93'
    if uom=='cubic centimetre per bar': return 'G94'
    if uom=='litre per bar': return 'G95'
    if uom=='cubic metre per bar': return 'G96'
    if uom=='millilitre per bar': return 'G97'
    if uom=='microhenry per kiloohm': return 'G98'
    if uom=='microhenry per ohm': return 'G99'
    if uom=='gallon (US) per day': return 'GB'
    if uom=='gigabecquerel': return 'GBQ'
    if uom=='gram, dry weight': return 'GDW'
    if uom=='pound per gallon (US)': return 'GE'
    if uom=='gram per metre (gram per 100 centimetres)': return 'GF'
    if uom=='gram of fissile isotope': return 'GFI'
    if uom=='great gross': return 'GGR'
    if uom=='gill (US)': return 'GIA'
    if uom=='gram, including container': return 'GIC'
    if uom=='gill (UK)': return 'GII'
    if uom=='gram, including inner packaging': return 'GIP'
    if uom=='gram per millilitre': return 'GJ'
    if uom=='gram per litre': return 'GL'
    if uom=='dry gallon (US)': return 'GLD'
    if uom=='gallon (UK)': return 'GLI'
    if uom=='gallon (US)': return 'GLL'
    if uom=='gram per square metre': return 'GM'
    if uom=='milligram per square metre': return 'GO'
    if uom=='milligram per cubic metre': return 'GP'
    if uom=='microgram per cubic metre': return 'GQ'
    if uom=='gram': return 'GRM'
    if uom=='grain': return 'GRN'
    if uom=='gross': return 'GRO'
    if uom=='gigajoule': return 'GV'
    if uom=='gigawatt hour': return 'GWH'
    if uom=='henry per kiloohm': return 'H03'
    if uom=='henry per ohm': return 'H04'
    if uom=='millihenry per kiloohm': return 'H05'
    if uom=='millihenry per ohm': return 'H06'
    if uom=='pascal second per bar': return 'H07'
    if uom=='microbecquerel': return 'H08'
    if uom=='reciprocal year': return 'H09'
    if uom=='reciprocal hour': return 'H10'
    if uom=='reciprocal month': return 'H11'
    if uom=='degree Celsius per hour': return 'H12'
    if uom=='degree Celsius per minute': return 'H13'
    if uom=='degree Celsius per second': return 'H14'
    if uom=='square centimetre per gram': return 'H15'
    if uom=='square decametre': return 'H16'
    if uom=='square hectometre': return 'H18'
    if uom=='cubic hectometre': return 'H19'
    if uom=='cubic kilometre': return 'H20'
    if uom=='blank': return 'H21'
    if uom=='volt square inch per pound-force': return 'H22'
    if uom=='volt per inch': return 'H23'
    if uom=='volt per microsecond': return 'H24'
    if uom=='percent per kelvin': return 'H25'
    if uom=='ohm per metre': return 'H26'
    if uom=='degree per metre': return 'H27'
    if uom=='microfarad per kilometre': return 'H28'
    if uom=='microgram per litre': return 'H29'
    if uom=='square micrometre (square micron)': return 'H30'
    if uom=='ampere per kilogram': return 'H31'
    if uom=='ampere squared second': return 'H32'
    if uom=='farad per kilometre': return 'H33'
    if uom=='hertz metre': return 'H34'
    if uom=='kelvin metre per watt': return 'H35'
    if uom=='megaohm per kilometre': return 'H36'
    if uom=='megaohm per metre': return 'H37'
    if uom=='megaampere': return 'H38'
    if uom=='megahertz kilometre': return 'H39'
    if uom=='newton per ampere': return 'H40'
    if uom=='newton metre watt to the power minus 0,5': return 'H41'
    if uom=='pascal per metre': return 'H42'
    if uom=='siemens per centimetre': return 'H43'
    if uom=='teraohm': return 'H44'
    if uom=='volt second per metre': return 'H45'
    if uom=='volt per second': return 'H46'
    if uom=='watt per cubic metre': return 'H47'
    if uom=='attofarad': return 'H48'
    if uom=='centimetre per hour': return 'H49'
    if uom=='reciprocal cubic centimetre': return 'H50'
    if uom=='decibel per kilometre': return 'H51'
    if uom=='decibel per metre': return 'H52'
    if uom=='kilogram per bar': return 'H53'
    if uom=='kilogram per cubic decimetre kelvin': return 'H54'
    if uom=='kilogram per cubic decimetre bar': return 'H55'
    if uom=='kilogram per square metre second': return 'H56'
    if uom=='inch per two pi radiant': return 'H57'
    if uom=='metre per volt second': return 'H58'
    if uom=='square metre per newton': return 'H59'
    if uom=='cubic metre per cubic metre': return 'H60'
    if uom=='millisiemens per centimetre': return 'H61'
    if uom=='millivolt per minute': return 'H62'
    if uom=='milligram per square centimetre': return 'H63'
    if uom=='milligram per gram': return 'H64'
    if uom=='millilitre per cubic metre': return 'H65'
    if uom=='millimetre per year': return 'H66'
    if uom=='millimetre per hour': return 'H67'
    if uom=='millimole per gram': return 'H68'
    if uom=='picopascal per kilometre': return 'H69'
    if uom=='picosecond': return 'H70'
    if uom=='percent per month': return 'H71'
    if uom=='percent per hectobar': return 'H72'
    if uom=='percent per decakelvin': return 'H73'
    if uom=='watt per metre': return 'H74'
    if uom=='decapascal': return 'H75'
    if uom=='gram per millimetre': return 'H76'
    if uom=='module width': return 'H77'
    if uom=='French gauge': return 'H79'
    if uom=='rack unit': return 'H80'
    if uom=='millimetre per minute': return 'H81'
    if uom=='big point': return 'H82'
    if uom=='litre per kilogram': return 'H83'
    if uom=='gram millimetre': return 'H84'
    if uom=='reciprocal week': return 'H85'
    if uom=='piece': return 'H87'
    if uom=='megaohm kilometre': return 'H88'
    if uom=='percent per ohm': return 'H89'
    if uom=='percent per degree': return 'H90'
    if uom=='percent per ten thousand': return 'H91'
    if uom=='percent per one hundred thousand': return 'H92'
    if uom=='percent per hundred': return 'H93'
    if uom=='percent per thousand': return 'H94'
    if uom=='percent per volt': return 'H95'
    if uom=='percent per bar': return 'H96'
    if uom=='percent per inch': return 'H98'
    if uom=='percent per metre': return 'H99'
    if uom=='hank': return 'HA'
    if uom=='hectobar': return 'HBA'
    if uom=='hundred boxes': return 'HBX'
    if uom=='hundred count': return 'HC'
    if uom=='hundred kilogram, dry weight': return 'HDW'
    if uom=='head': return 'HEA'
    if uom=='hectogram': return 'HGM'
    if uom=='hundred cubic foot': return 'HH'
    if uom=='hundred international unit': return 'HIU'
    if uom=='hundred kilogram, net mass': return 'HKM'
    if uom=='hectolitre': return 'HLT'
    if uom=='mile per hour (statute mile)': return 'HM'
    if uom=='million cubic metre': return 'HMQ'
    if uom=='hectometre': return 'HMT'
    if uom=='hectolitre of pure alcohol': return 'HPA'
    if uom=='hertz': return 'HTZ'
    if uom=='hour': return 'HUR'
    if uom=='inch pound (pound inch)': return 'IA'
    if uom=='person': return 'IE'
    if uom=='inch': return 'INH'
    if uom=='square inch': return 'INK'
    if uom=='cubic inch': return 'INQ'
    if uom=='international sugar degree': return 'ISD'
    if uom=='inch per second': return 'IU'
    if uom=='international unit per gram': return 'IUG'
    if uom=='inch per second squared': return 'IV'
    if uom=='percent per millimetre': return 'J10'
    if uom=='per mille per psi': return 'J12'
    if uom=='degree API': return 'J13'
    if uom=='degree Baume (origin scale)': return 'J14'
    if uom=='degree Baume (US heavy)': return 'J15'
    if uom=='degree Baume (US light)': return 'J16'
    if uom=='degree Balling': return 'J17'
    if uom=='degree Brix': return 'J18'
    if uom=='degree Fahrenheit hour square foot per British thermal unit (thermochemical)': return 'J19'
    if uom=='joule per kilogram': return 'J2'
    if uom=='degree Fahrenheit per kelvin': return 'J20'
    if uom=='degree Fahrenheit per bar': return 'J21'
    if uom=='degree Fahrenheit hour square foot per British thermal unit (international table)': return 'J22'
    if uom=='degree Fahrenheit per hour': return 'J23'
    if uom=='degree Fahrenheit per minute': return 'J24'
    if uom=='degree Fahrenheit per second': return 'J25'
    if uom=='reciprocal degree Fahrenheit': return 'J26'
    if uom=='degree Oechsle': return 'J27'
    if uom=='degree Rankine per hour': return 'J28'
    if uom=='degree Rankine per minute': return 'J29'
    if uom=='degree Rankine per second': return 'J30'
    if uom=='degree Twaddell': return 'J31'
    if uom=='micropoise': return 'J32'
    if uom=='microgram per kilogram': return 'J33'
    if uom=='microgram per cubic metre kelvin': return 'J34'
    if uom=='microgram per cubic metre bar': return 'J35'
    if uom=='microlitre per litre': return 'J36'
    if uom=='baud': return 'J38'
    if uom=='British thermal unit (mean)': return 'J39'
    if uom=='British thermal unit (international table) foot per hour square foot degree Fahrenheit': return 'J40'
    if uom=='British thermal unit (international table) inch per hour square foot degree Fahrenheit': return 'J41'
    if uom=='British thermal unit (international table) inch per second square foot degree Fahrenheit': return 'J42'
    if uom=='British thermal unit (international table) per pound degree Fahrenheit': return 'J43'
    if uom=='British thermal unit (international table) per minute': return 'J44'
    if uom=='British thermal unit (international table) per second': return 'J45'
    if uom=='British thermal unit (thermochemical) foot per hour square foot degree Fahrenheit': return 'J46'
    if uom=='British thermal unit (thermochemical) per hour': return 'J47'
    if uom=='British thermal unit (thermochemical) inch per hour square foot degree Fahrenheit': return 'J48'
    if uom=='British thermal unit (thermochemical) inch per second square foot degree Fahrenheit': return 'J49'
    if uom=='British thermal unit (thermochemical) per pound degree Fahrenheit': return 'J50'
    if uom=='British thermal unit (thermochemical) per minute': return 'J51'
    if uom=='British thermal unit (thermochemical) per second': return 'J52'
    if uom=='coulomb square metre per kilogram': return 'J53'
    if uom=='megabaud': return 'J54'
    if uom=='watt second': return 'J55'
    if uom=='bar per bar': return 'J56'
    if uom=='barrel (UK petroleum)': return 'J57'
    if uom=='barrel (UK petroleum) per minute': return 'J58'
    if uom=='barrel (UK petroleum) per day': return 'J59'
    if uom=='barrel (UK petroleum) per hour': return 'J60'
    if uom=='barrel (UK petroleum) per second': return 'J61'
    if uom=='barrel (US petroleum) per hour': return 'J62'
    if uom=='barrel (US petroleum) per second': return 'J63'
    if uom=='bushel (UK) per day': return 'J64'
    if uom=='bushel (UK) per hour': return 'J65'
    if uom=='bushel (UK) per minute': return 'J66'
    if uom=='bushel (UK) per second': return 'J67'
    if uom=='bushel (US dry) per day': return 'J68'
    if uom=='bushel (US dry) per hour': return 'J69'
    if uom=='bushel (US dry) per minute': return 'J70'
    if uom=='bushel (US dry) per second': return 'J71'
    if uom=='centinewton metre': return 'J72'
    if uom=='centipoise per kelvin': return 'J73'
    if uom=='centipoise per bar': return 'J74'
    if uom=='calorie (mean)': return 'J75'
    if uom=='calorie (international table) per gram degree Celsius': return 'J76'
    if uom=='calorie (thermochemical) per centimetre second degree Celsius': return 'J78'
    if uom=='calorie (thermochemical) per gram degree Celsius': return 'J79'
    if uom=='calorie (thermochemical) per minute': return 'J81'
    if uom=='calorie (thermochemical) per second': return 'J82'
    if uom=='clo': return 'J83'
    if uom=='centimetre per second kelvin': return 'J84'
    if uom=='centimetre per second bar': return 'J85'
    if uom=='cubic centimetre per cubic metre': return 'J87'
    if uom=='cubic decimetre per day': return 'J90'
    if uom=='cubic decimetre per cubic metre': return 'J91'
    if uom=='cubic decimetre per minute': return 'J92'
    if uom=='cubic decimetre per second': return 'J93'
    if uom=='ounce (UK fluid) per day': return 'J95'
    if uom=='ounce (UK fluid) per hour': return 'J96'
    if uom=='ounce (UK fluid) per minute': return 'J97'
    if uom=='ounce (UK fluid) per second': return 'J98'
    if uom=='ounce (US fluid) per day': return 'J99'
    if uom=='joule per kelvin': return 'JE'
    if uom=='megajoule per kilogram': return 'JK'
    if uom=='megajoule per cubic metre': return 'JM'
    if uom=='pipeline joint': return 'JNT'
    if uom=='joule': return 'JOU'
    if uom=='hundred metre': return 'JPS'
    if uom=='number of jewels': return 'JWL'
    if uom=='kilowatt demand': return 'K1'
    if uom=='ounce (US fluid) per hour': return 'K10'
    if uom=='ounce (US fluid) per minute': return 'K11'
    if uom=='ounce (US fluid) per second': return 'K12'
    if uom=='foot per degree Fahrenheit': return 'K13'
    if uom=='foot per hour': return 'K14'
    if uom=='foot pound-force per hour': return 'K15'
    if uom=='foot pound-force per minute': return 'K16'
    if uom=='foot per psi': return 'K17'
    if uom=='foot per second degree Fahrenheit': return 'K18'
    if uom=='foot per second psi': return 'K19'
    if uom=='kilovolt ampere reactive demand': return 'K2'
    if uom=='reciprocal cubic foot': return 'K20'
    if uom=='cubic foot per degree Fahrenheit': return 'K21'
    if uom=='cubic foot per day': return 'K22'
    if uom=='cubic foot per psi': return 'K23'
    if uom=='gallon (UK) per day': return 'K26'
    if uom=='gallon (UK) per hour': return 'K27'
    if uom=='gallon (UK) per second': return 'K28'
    if uom=='kilovolt ampere reactive hour': return 'K3'
    if uom=='gallon (US liquid) per second': return 'K30'
    if uom=='gram-force per square centimetre': return 'K31'
    if uom=='gill (UK) per day': return 'K32'
    if uom=='gill (UK) per hour': return 'K33'
    if uom=='gill (UK) per minute': return 'K34'
    if uom=='gill (UK) per second': return 'K35'
    if uom=='gill (US) per day': return 'K36'
    if uom=='gill (US) per hour': return 'K37'
    if uom=='gill (US) per minute': return 'K38'
    if uom=='gill (US) per second': return 'K39'
    if uom=='standard acceleration of free fall': return 'K40'
    if uom=='grain per gallon (US)': return 'K41'
    if uom=='horsepower (boiler)': return 'K42'
    if uom=='horsepower (electric)': return 'K43'
    if uom=='inch per degree Fahrenheit': return 'K45'
    if uom=='inch per psi': return 'K46'
    if uom=='inch per second degree Fahrenheit': return 'K47'
    if uom=='inch per second psi': return 'K48'
    if uom=='reciprocal cubic inch': return 'K49'
    if uom=='kilobaud': return 'K50'
    if uom=='kilocalorie (mean)': return 'K51'
    if uom=='kilocalorie (international table) per hour metre degree Celsius': return 'K52'
    if uom=='kilocalorie (thermochemical)': return 'K53'
    if uom=='kilocalorie (thermochemical) per minute': return 'K54'
    if uom=='kilocalorie (thermochemical) per second': return 'K55'
    if uom=='kilomole per hour': return 'K58'
    if uom=='kilomole per cubic metre kelvin': return 'K59'
    if uom=='kilolitre': return 'K6'
    if uom=='kilomole per cubic metre bar': return 'K60'
    if uom=='kilomole per minute': return 'K61'
    if uom=='litre per litre': return 'K62'
    if uom=='reciprocal litre': return 'K63'
    if uom=='pound (avoirdupois) per degree Fahrenheit': return 'K64'
    if uom=='pound (avoirdupois) square foot': return 'K65'
    if uom=='pound (avoirdupois) per day': return 'K66'
    if uom=='pound per foot hour': return 'K67'
    if uom=='pound per foot second': return 'K68'
    if uom=='pound (avoirdupois) per cubic foot degree Fahrenheit': return 'K69'
    if uom=='pound (avoirdupois) per cubic foot psi': return 'K70'
    if uom=='pound (avoirdupois) per gallon (UK)': return 'K71'
    if uom=='pound (avoirdupois) per hour degree Fahrenheit': return 'K73'
    if uom=='pound (avoirdupois) per hour psi': return 'K74'
    if uom=='pound (avoirdupois) per cubic inch degree Fahrenheit': return 'K75'
    if uom=='pound (avoirdupois) per cubic inch psi': return 'K76'
    if uom=='pound (avoirdupois) per psi': return 'K77'
    if uom=='pound (avoirdupois) per minute': return 'K78'
    if uom=='pound (avoirdupois) per minute degree Fahrenheit': return 'K79'
    if uom=='pound (avoirdupois) per minute psi': return 'K80'
    if uom=='pound (avoirdupois) per second': return 'K81'
    if uom=='pound (avoirdupois) per second degree Fahrenheit': return 'K82'
    if uom=='pound (avoirdupois) per second psi': return 'K83'
    if uom=='pound per cubic yard': return 'K84'
    if uom=='pound-force per square foot': return 'K85'
    if uom=='pound-force per square inch degree Fahrenheit': return 'K86'
    if uom=='psi cubic inch per second': return 'K87'
    if uom=='psi litre per second': return 'K88'
    if uom=='psi cubic metre per second': return 'K89'
    if uom=='psi cubic yard per second': return 'K90'
    if uom=='pound-force second per square foot': return 'K91'
    if uom=='pound-force second per square inch': return 'K92'
    if uom=='reciprocal psi': return 'K93'
    if uom=='quart (UK liquid) per day': return 'K94'
    if uom=='quart (UK liquid) per hour': return 'K95'
    if uom=='quart (UK liquid) per minute': return 'K96'
    if uom=='quart (UK liquid) per second': return 'K97'
    if uom=='quart (US liquid) per day': return 'K98'
    if uom=='quart (US liquid) per hour': return 'K99'
    if uom=='cake': return 'KA'
    if uom=='katal': return 'KAT'
    if uom=='kilocharacter': return 'KB'
    if uom=='kilobar': return 'KBA'
    if uom=='kilogram of choline chloride': return 'KCC'
    if uom=='kilogram drained net weight': return 'KDW'
    if uom=='kelvin': return 'KEL'
    if uom=='kilogram': return 'KGM'
    if uom=='kilogram per second': return 'KGS'
    if uom=='kilogram of hydrogen peroxide': return 'KHY'
    if uom=='kilohertz': return 'KHZ'
    if uom=='kilogram per millimetre width': return 'KI'
    if uom=='kilogram, including container': return 'KIC'
    if uom=='kilogram, including inner packaging': return 'KIP'
    if uom=='kilosegment': return 'KJ'
    if uom=='kilojoule': return 'KJO'
    if uom=='kilogram per metre': return 'KL'
    if uom=='lactic dry material percentage': return 'KLK'
    if uom=='kilolux': return 'KLX'
    if uom=='kilogram of methylamine': return 'KMA'
    if uom=='kilometre per hour': return 'KMH'
    if uom=='square kilometre': return 'KMK'
    if uom=='kilogram per cubic metre': return 'KMQ'
    if uom=='kilometre': return 'KMT'
    if uom=='kilogram of nitrogen': return 'KNI'
    if uom=='kilonewton per square metre': return 'KNM'
    if uom=='kilogram named substance': return 'KNS'
    if uom=='knot': return 'KNT'
    if uom=='milliequivalence caustic potash per gram of product': return 'KO'
    if uom=='kilopascal': return 'KPA'
    if uom=='kilogram of potassium hydroxide (caustic potash)': return 'KPH'
    if uom=='kilogram of potassium oxide': return 'KPO'
    if uom=='kilogram of phosphorus pentoxide (phosphoric anhydride)': return 'KPP'
    if uom=='kiloroentgen': return 'KR'
    if uom=='kilogram of substance 90 % dry': return 'KSD'
    if uom=='kilogram of sodium hydroxide (caustic soda)': return 'KSH'
    if uom=='kit': return 'KT'
    if uom=='kilotonne': return 'KTN'
    if uom=='kilogram of uranium': return 'KUR'
    if uom=='kilovolt - ampere': return 'KVA'
    if uom=='kilovar': return 'KVR'
    if uom=='kilovolt': return 'KVT'
    if uom=='kilogram per millimetre': return 'KW'
    if uom=='kilowatt hour': return 'KWH'
    if uom=='Kilowatt hour per normalized cubic metre': return 'KWN'
    if uom=='kilogram of tungsten trioxide': return 'KWO'
    if uom=='Kilowatt hour per standard cubic metre': return 'KWS'
    if uom=='kilowatt': return 'KWT'
    if uom=='millilitre per kilogram': return 'KX'
    if uom=='quart (US liquid) per minute': return 'L10'
    if uom=='quart (US liquid) per second': return 'L11'
    if uom=='metre per second kelvin': return 'L12'
    if uom=='metre per second bar': return 'L13'
    if uom=='square metre hour degree Celsius per kilocalorie (international table)': return 'L14'
    if uom=='millipascal second per kelvin': return 'L15'
    if uom=='millipascal second per bar': return 'L16'
    if uom=='milligram per cubic metre kelvin': return 'L17'
    if uom=='milligram per cubic metre bar': return 'L18'
    if uom=='millilitre per litre': return 'L19'
    if uom=='litre per minute': return 'L2'
    if uom=='reciprocal cubic millimetre': return 'L20'
    if uom=='cubic millimetre per cubic metre': return 'L21'
    if uom=='mole per hour': return 'L23'
    if uom=='mole per kilogram kelvin': return 'L24'
    if uom=='mole per kilogram bar': return 'L25'
    if uom=='mole per litre kelvin': return 'L26'
    if uom=='mole per litre bar': return 'L27'
    if uom=='mole per cubic metre kelvin': return 'L28'
    if uom=='mole per cubic metre bar': return 'L29'
    if uom=='mole per minute': return 'L30'
    if uom=='milliroentgen aequivalent men': return 'L31'
    if uom=='nanogram per kilogram': return 'L32'
    if uom=='ounce (avoirdupois) per day': return 'L33'
    if uom=='ounce (avoirdupois) per hour': return 'L34'
    if uom=='ounce (avoirdupois) per minute': return 'L35'
    if uom=='ounce (avoirdupois) per second': return 'L36'
    if uom=='ounce (avoirdupois) per gallon (UK)': return 'L37'
    if uom=='ounce (avoirdupois) per gallon (US)': return 'L38'
    if uom=='ounce (avoirdupois) per cubic inch': return 'L39'
    if uom=='ounce (avoirdupois)-force': return 'L40'
    if uom=='ounce (avoirdupois)-force inch': return 'L41'
    if uom=='picosiemens per metre': return 'L42'
    if uom=='peck (UK)': return 'L43'
    if uom=='peck (UK) per day': return 'L44'
    if uom=='peck (UK) per hour': return 'L45'
    if uom=='peck (UK) per minute': return 'L46'
    if uom=='peck (UK) per second': return 'L47'
    if uom=='peck (US dry) per day': return 'L48'
    if uom=='peck (US dry) per hour': return 'L49'
    if uom=='peck (US dry) per minute': return 'L50'
    if uom=='peck (US dry) per second': return 'L51'
    if uom=='psi per psi': return 'L52'
    if uom=='pint (UK) per day': return 'L53'
    if uom=='pint (UK) per hour': return 'L54'
    if uom=='pint (UK) per minute': return 'L55'
    if uom=='pint (UK) per second': return 'L56'
    if uom=='pint (US liquid) per day': return 'L57'
    if uom=='pint (US liquid) per hour': return 'L58'
    if uom=='pint (US liquid) per minute': return 'L59'
    if uom=='pint (US liquid) per second': return 'L60'
    if uom=='slug per day': return 'L63'
    if uom=='slug per foot second': return 'L64'
    if uom=='slug per cubic foot': return 'L65'
    if uom=='slug per hour': return 'L66'
    if uom=='slug per minute': return 'L67'
    if uom=='slug per second': return 'L68'
    if uom=='tonne per kelvin': return 'L69'
    if uom=='tonne per bar': return 'L70'
    if uom=='tonne per day': return 'L71'
    if uom=='tonne per day kelvin': return 'L72'
    if uom=='tonne per day bar': return 'L73'
    if uom=='tonne per hour kelvin': return 'L74'
    if uom=='tonne per hour bar': return 'L75'
    if uom=='tonne per cubic metre kelvin': return 'L76'
    if uom=='tonne per cubic metre bar': return 'L77'
    if uom=='tonne per minute': return 'L78'
    if uom=='tonne per minute kelvin': return 'L79'
    if uom=='tonne per minute bar': return 'L80'
    if uom=='tonne per second': return 'L81'
    if uom=='tonne per second kelvin': return 'L82'
    if uom=='tonne per second bar': return 'L83'
    if uom=='ton (UK shipping)': return 'L84'
    if uom=='ton long per day': return 'L85'
    if uom=='ton (US shipping)': return 'L86'
    if uom=='ton short per degree Fahrenheit': return 'L87'
    if uom=='ton short per day': return 'L88'
    if uom=='ton short per hour degree Fahrenheit': return 'L89'
    if uom=='ton short per hour psi': return 'L90'
    if uom=='ton short per psi': return 'L91'
    if uom=='ton (UK long) per cubic yard': return 'L92'
    if uom=='ton (US short) per cubic yard': return 'L93'
    if uom=='ton-force (US short)': return 'L94'
    if uom=='common year': return 'L95'
    if uom=='sidereal year': return 'L96'
    if uom=='yard per degree Fahrenheit': return 'L98'
    if uom=='yard per psi': return 'L99'
    if uom=='pound per cubic inch': return 'LA'
    if uom=='lactose excess percentage': return 'LAC'
    if uom=='pound': return 'LBR'
    if uom=='troy pound (US)': return 'LBT'
    if uom=='litre per day': return 'LD'
    if uom=='leaf': return 'LEF'
    if uom=='linear foot': return 'LF'
    if uom=='labour hour': return 'LH'
    if uom=='link': return 'LK'
    if uom=='linear metre': return 'LM'
    if uom=='length': return 'LN'
    if uom=='lot [unit of procurement]': return 'LO'
    if uom=='liquid pound': return 'LP'
    if uom=='litre of pure alcohol': return 'LPA'
    if uom=='layer': return 'LR'
    if uom=='lump sum': return 'LS'
    if uom=='ton (UK) or long ton (US)': return 'LTN'
    if uom=='litre': return 'LTR'
    if uom=='metric ton, lubricating oil': return 'LUB'
    if uom=='lumen': return 'LUM'
    if uom=='lux': return 'LUX'
    if uom=='linear yard': return 'LY'
    if uom=='milligram per litre': return 'M1'
    if uom=='reciprocal cubic yard': return 'M10'
    if uom=='cubic yard per degree Fahrenheit': return 'M11'
    if uom=='cubic yard per day': return 'M12'
    if uom=='cubic yard per hour': return 'M13'
    if uom=='cubic yard per psi': return 'M14'
    if uom=='cubic yard per minute': return 'M15'
    if uom=='cubic yard per second': return 'M16'
    if uom=='kilohertz metre': return 'M17'
    if uom=='gigahertz metre': return 'M18'
    if uom=='Beaufort': return 'M19'
    if uom=='reciprocal megakelvin or megakelvin to the power minus one': return 'M20'
    if uom=='reciprocal kilovolt - ampere reciprocal hour': return 'M21'
    if uom=='millilitre per square centimetre minute': return 'M22'
    if uom=='newton per centimetre': return 'M23'
    if uom=='ohm kilometre': return 'M24'
    if uom=='percent per degree Celsius': return 'M25'
    if uom=='gigaohm per metre': return 'M26'
    if uom=='megahertz metre': return 'M27'
    if uom=='kilogram per kilogram': return 'M29'
    if uom=='reciprocal volt - ampere reciprocal second': return 'M30'
    if uom=='kilogram per kilometre': return 'M31'
    if uom=='pascal second per litre': return 'M32'
    if uom=='millimole per litre': return 'M33'
    if uom=='newton metre per square metre': return 'M34'
    if uom=='millivolt - ampere': return 'M35'
    if uom=='30-day month': return 'M36'
    if uom=='actual/360': return 'M37'
    if uom=='kilometre per second squared': return 'M38'
    if uom=='centimetre per second squared': return 'M39'
    if uom=='monetary value': return 'M4'
    if uom=='yard per second squared': return 'M40'
    if uom=='millimetre per second squared': return 'M41'
    if uom=='mile (statute mile) per second squared': return 'M42'
    if uom=='mil': return 'M43'
    if uom=='revolution': return 'M44'
    if uom=='degree [unit of angle] per second squared': return 'M45'
    if uom=='revolution per minute': return 'M46'
    if uom=='circular mil': return 'M47'
    if uom=='square mile (based on U.S. survey foot)': return 'M48'
    if uom=='chain (based on U.S. survey foot)': return 'M49'
    if uom=='microcurie': return 'M5'
    if uom=='furlong': return 'M50'
    if uom=='foot (U.S. survey)': return 'M51'
    if uom=='mile (based on U.S. survey foot)': return 'M52'
    if uom=='metre per pascal': return 'M53'
    if uom=='metre per radiant': return 'M55'
    if uom=='shake': return 'M56'
    if uom=='mile per minute': return 'M57'
    if uom=='mile per second': return 'M58'
    if uom=='metre per second pascal': return 'M59'
    if uom=='metre per hour': return 'M60'
    if uom=='inch per year': return 'M61'
    if uom=='kilometre per second': return 'M62'
    if uom=='inch per minute': return 'M63'
    if uom=='yard per second': return 'M64'
    if uom=='yard per minute': return 'M65'
    if uom=='yard per hour': return 'M66'
    if uom=='acre-foot (based on U.S. survey foot)': return 'M67'
    if uom=='cord (128 ft3)': return 'M68'
    if uom=='cubic mile (UK statute)': return 'M69'
    if uom=='micro-inch': return 'M7'
    if uom=='ton, register': return 'M70'
    if uom=='cubic metre per pascal': return 'M71'
    if uom=='bel': return 'M72'
    if uom=='kilogram per cubic metre pascal': return 'M73'
    if uom=='kilogram per pascal': return 'M74'
    if uom=='kilopound-force': return 'M75'
    if uom=='poundal': return 'M76'
    if uom=='kilogram metre per second squared': return 'M77'
    if uom=='pond': return 'M78'
    if uom=='square foot per hour': return 'M79'
    if uom=='stokes per pascal': return 'M80'
    if uom=='square centimetre per second': return 'M81'
    if uom=='square metre per second pascal': return 'M82'
    if uom=='denier': return 'M83'
    if uom=='pound per yard': return 'M84'
    if uom=='ton, assay': return 'M85'
    if uom=='pfund': return 'M86'
    if uom=='kilogram per second pascal': return 'M87'
    if uom=='tonne per month': return 'M88'
    if uom=='tonne per year': return 'M89'
    if uom=='million Btu per 1000 cubic foot': return 'M9'
    if uom=='kilopound per hour': return 'M90'
    if uom=='pound per pound': return 'M91'
    if uom=='pound-force foot': return 'M92'
    if uom=='newton metre per radian': return 'M93'
    if uom=='kilogram metre': return 'M94'
    if uom=='poundal foot': return 'M95'
    if uom=='poundal inch': return 'M96'
    if uom=='dyne metre': return 'M97'
    if uom=='kilogram centimetre per second': return 'M98'
    if uom=='gram centimetre per second': return 'M99'
    if uom=='megavolt ampere reactive hour': return 'MAH'
    if uom=='megalitre': return 'MAL'
    if uom=='megametre': return 'MAM'
    if uom=='megavar': return 'MAR'
    if uom=='megawatt': return 'MAW'
    if uom=='thousand standard brick equivalent': return 'MBE'
    if uom=='thousand board foot': return 'MBF'
    if uom=='millibar': return 'MBR'
    if uom=='microgram': return 'MC'
    if uom=='millicurie': return 'MCU'
    if uom=='air dry metric ton': return 'MD'
    if uom=='milligram': return 'MGM'
    if uom=='megahertz': return 'MHZ'
    if uom=='square mile (statute mile)': return 'MIK'
    if uom=='thousand': return 'MIL'
    if uom=='minute [unit of time]': return 'MIN'
    if uom=='million': return 'MIO'
    if uom=='million international unit': return 'MIU'
    if uom=='milliard': return 'MLD'
    if uom=='millilitre': return 'MLT'
    if uom=='square millimetre': return 'MMK'
    if uom=='cubic millimetre': return 'MMQ'
    if uom=='millimetre': return 'MMT'
    if uom=='kilogram, dry weight': return 'MND'
    if uom=='month': return 'MON'
    if uom=='megapascal': return 'MPA'
    if uom=='cubic metre per hour': return 'MQH'
    if uom=='cubic metre per second': return 'MQS'
    if uom=='metre per second squared': return 'MSK'
    if uom=='square metre': return 'MTK'
    if uom=='cubic metre': return 'MTQ'
    if uom=='metre': return 'MTR'
    if uom=='metre per second': return 'MTS'
    if uom=='megavolt - ampere': return 'MVA'
    if uom=='megawatt hour (1000 kW.h)': return 'MWH'
    if uom=='pen calorie': return 'N1'
    if uom=='pound foot per second': return 'N10'
    if uom=='pound inch per second': return 'N11'
    if uom=='Pferdestaerke': return 'N12'
    if uom=='centimetre of mercury (0 ºC)': return 'N13'
    if uom=='centimetre of water (4 ºC)': return 'N14'
    if uom=='foot of water (39.2 ºF)': return 'N15'
    if uom=='inch of mercury (32 ºF)': return 'N16'
    if uom=='inch of mercury (60 ºF)': return 'N17'
    if uom=='inch of water (39.2 ºF)': return 'N18'
    if uom=='inch of water (60 ºF)': return 'N19'
    if uom=='kip per square inch': return 'N20'
    if uom=='poundal per square foot': return 'N21'
    if uom=='ounce (avoirdupois) per square inch': return 'N22'
    if uom=='conventional metre of water': return 'N23'
    if uom=='gram per square millimetre': return 'N24'
    if uom=='pound per square yard': return 'N25'
    if uom=='poundal per square inch': return 'N26'
    if uom=='foot to the fourth power': return 'N27'
    if uom=='cubic decimetre per kilogram': return 'N28'
    if uom=='cubic foot per pound': return 'N29'
    if uom=='print point': return 'N3'
    if uom=='cubic inch per pound': return 'N30'
    if uom=='kilonewton per metre': return 'N31'
    if uom=='poundal per inch': return 'N32'
    if uom=='pound-force per yard': return 'N33'
    if uom=='poundal second per square foot': return 'N34'
    if uom=='poise per pascal': return 'N35'
    if uom=='newton second per square metre': return 'N36'
    if uom=='kilogram per metre second': return 'N37'
    if uom=='kilogram per metre minute': return 'N38'
    if uom=='kilogram per metre day': return 'N39'
    if uom=='kilogram per metre hour': return 'N40'
    if uom=='gram per centimetre second': return 'N41'
    if uom=='poundal second per square inch': return 'N42'
    if uom=='pound per foot minute': return 'N43'
    if uom=='pound per foot day': return 'N44'
    if uom=='cubic metre per second pascal': return 'N45'
    if uom=='foot poundal': return 'N46'
    if uom=='inch poundal': return 'N47'
    if uom=='watt per square centimetre': return 'N48'
    if uom=='watt per square inch': return 'N49'
    if uom=='British thermal unit (international table) per square foot hour': return 'N50'
    if uom=='British thermal unit (thermochemical) per square foot hour': return 'N51'
    if uom=='British thermal unit (thermochemical) per square foot minute': return 'N52'
    if uom=='British thermal unit (international table) per square foot second': return 'N53'
    if uom=='British thermal unit (thermochemical) per square foot second': return 'N54'
    if uom=='British thermal unit (international table) per square inch second': return 'N55'
    if uom=='calorie (thermochemical) per square centimetre minute': return 'N56'
    if uom=='calorie (thermochemical) per square centimetre second': return 'N57'
    if uom=='British thermal unit (international table) per cubic foot': return 'N58'
    if uom=='British thermal unit (thermochemical) per cubic foot': return 'N59'
    if uom=='British thermal unit (international table) per degree Fahrenheit': return 'N60'
    if uom=='British thermal unit (thermochemical) per degree Fahrenheit': return 'N61'
    if uom=='British thermal unit (international table) per degree Rankine': return 'N62'
    if uom=='British thermal unit (thermochemical) per degree Rankine': return 'N63'
    if uom=='British thermal unit (thermochemical) per pound degree Rankine': return 'N64'
    if uom=='kilocalorie (international table) per gram kelvin': return 'N65'
    if uom=='British thermal unit (39 ºF)': return 'N66'
    if uom=='British thermal unit (59 ºF)': return 'N67'
    if uom=='British thermal unit (60 ºF)': return 'N68'
    if uom=='calorie (20 ºC)': return 'N69'
    if uom=='quad (1015 BtuIT)': return 'N70'
    if uom=='therm (EC)': return 'N71'
    if uom=='therm (U.S.)': return 'N72'
    if uom=='British thermal unit (thermochemical) per pound': return 'N73'
    if uom=='British thermal unit (international table) per hour square foot degree Fahrenheit': return 'N74'
    if uom=='British thermal unit (thermochemical) per hour square foot degree Fahrenheit': return 'N75'
    if uom=='British thermal unit (international table) per second square foot degree Fahrenheit': return 'N76'
    if uom=='British thermal unit (thermochemical) per second square foot degree Fahrenheit': return 'N77'
    if uom=='kilowatt per square metre kelvin': return 'N78'
    if uom=='kelvin per pascal': return 'N79'
    if uom=='watt per metre degree Celsius': return 'N80'
    if uom=='kilowatt per metre kelvin': return 'N81'
    if uom=='kilowatt per metre degree Celsius': return 'N82'
    if uom=='metre per degree Celcius metre': return 'N83'
    if uom=='degree Fahrenheit hour per British thermal unit (international table)': return 'N84'
    if uom=='degree Fahrenheit hour per British thermal unit (thermochemical)': return 'N85'
    if uom=='degree Fahrenheit second per British thermal unit (international table)': return 'N86'
    if uom=='degree Fahrenheit second per British thermal unit (thermochemical)': return 'N87'
    if uom=='degree Fahrenheit hour square foot per British thermal unit (international table) inch': return 'N88'
    if uom=='degree Fahrenheit hour square foot per British thermal unit (thermochemical) inch': return 'N89'
    if uom=='kilofarad': return 'N90'
    if uom=='reciprocal joule': return 'N91'
    if uom=='picosiemens': return 'N92'
    if uom=='ampere per pascal': return 'N93'
    if uom=='franklin': return 'N94'
    if uom=='ampere minute': return 'N95'
    if uom=='biot': return 'N96'
    if uom=='gilbert': return 'N97'
    if uom=='volt per pascal': return 'N98'
    if uom=='picovolt': return 'N99'
    if uom=='milligram per kilogram': return 'NA'
    if uom=='number of articles': return 'NAR'
    if uom=='number of cells': return 'NCL'
    if uom=='newton': return 'NEW'
    if uom=='message': return 'NF'
    if uom=='nil': return 'NIL'
    if uom=='number of international units': return 'NIU'
    if uom=='load': return 'NL'
    if uom=='Normalised cubic metre': return 'NM3'
    if uom=='nautical mile': return 'NMI'
    if uom=='number of packs': return 'NMP'
    if uom=='number of parts': return 'NPT'
    if uom=='net ton': return 'NT'
    if uom=='newton metre': return 'NU'
    if uom=='part per thousand': return 'NX'
    if uom=='panel': return 'OA'
    if uom=='ozone depletion equivalent': return 'ODE'
    if uom=='ODS Grams': return 'ODG'
    if uom=='ODS Kilograms': return 'ODK'
    if uom=='ODS Milligrams': return 'ODM'
    if uom=='ohm': return 'OHM'
    if uom=='ounce per square yard': return 'ON'
    if uom=='ounce (avoirdupois)': return 'ONZ'
    if uom=='oscillations per minute': return 'OPM'
    if uom=='overtime hour': return 'OT'
    if uom=='fluid ounce (US)': return 'OZA'
    if uom=='fluid ounce (UK)': return 'OZI'
    if uom=='percent': return 'P1'
    if uom=='coulomb per metre': return 'P10'
    if uom=='kiloweber': return 'P11'
    if uom=='gamma': return 'P12'
    if uom=='kilotesla': return 'P13'
    if uom=='joule per second': return 'P14'
    if uom=='joule per minute': return 'P15'
    if uom=='joule per hour': return 'P16'
    if uom=='joule per day': return 'P17'
    if uom=='kilojoule per second': return 'P18'
    if uom=='kilojoule per minute': return 'P19'
    if uom=='pound per foot': return 'P2'
    if uom=='kilojoule per hour': return 'P20'
    if uom=='kilojoule per day': return 'P21'
    if uom=='nanoohm': return 'P22'
    if uom=='ohm circular-mil per foot': return 'P23'
    if uom=='kilohenry': return 'P24'
    if uom=='lumen per square foot': return 'P25'
    if uom=='phot': return 'P26'
    if uom=='footcandle': return 'P27'
    if uom=='candela per square inch': return 'P28'
    if uom=='footlambert': return 'P29'
    if uom=='lambert': return 'P30'
    if uom=='stilb': return 'P31'
    if uom=='candela per square foot': return 'P32'
    if uom=='kilocandela': return 'P33'
    if uom=='millicandela': return 'P34'
    if uom=='Hefner-Kerze': return 'P35'
    if uom=='international candle': return 'P36'
    if uom=='British thermal unit (international table) per square foot': return 'P37'
    if uom=='British thermal unit (thermochemical) per square foot': return 'P38'
    if uom=='calorie (thermochemical) per square centimetre': return 'P39'
    if uom=='langley': return 'P40'
    if uom=='decade (logarithmic)': return 'P41'
    if uom=='pascal squared second': return 'P42'
    if uom=='bel per metre': return 'P43'
    if uom=='pound mole': return 'P44'
    if uom=='pound mole per second': return 'P45'
    if uom=='pound mole per minute': return 'P46'
    if uom=='kilomole per kilogram': return 'P47'
    if uom=='pound mole per pound': return 'P48'
    if uom=='newton square metre per ampere': return 'P49'
    if uom=='five pack': return 'P5'
    if uom=='weber metre': return 'P50'
    if uom=='mol per kilogram pascal': return 'P51'
    if uom=='mol per cubic metre pascal': return 'P52'
    if uom=='unit pole': return 'P53'
    if uom=='milligray per second': return 'P54'
    if uom=='microgray per second': return 'P55'
    if uom=='nanogray per second': return 'P56'
    if uom=='gray per minute': return 'P57'
    if uom=='milligray per minute': return 'P58'
    if uom=='microgray per minute': return 'P59'
    if uom=='nanogray per minute': return 'P60'
    if uom=='gray per hour': return 'P61'
    if uom=='milligray per hour': return 'P62'
    if uom=='microgray per hour': return 'P63'
    if uom=='nanogray per hour': return 'P64'
    if uom=='sievert per second': return 'P65'
    if uom=='millisievert per second': return 'P66'
    if uom=='microsievert per second': return 'P67'
    if uom=='nanosievert per second': return 'P68'
    if uom=='rem per second': return 'P69'
    if uom=='sievert per hour': return 'P70'
    if uom=='millisievert per hour': return 'P71'
    if uom=='microsievert per hour': return 'P72'
    if uom=='nanosievert per hour': return 'P73'
    if uom=='sievert per minute': return 'P74'
    if uom=='millisievert per minute': return 'P75'
    if uom=='microsievert per minute': return 'P76'
    if uom=='nanosievert per minute': return 'P77'
    if uom=='reciprocal square inch': return 'P78'
    if uom=='pascal square metre per kilogram': return 'P79'
    if uom=='millipascal per metre': return 'P80'
    if uom=='kilopascal per metre': return 'P81'
    if uom=='hectopascal per metre': return 'P82'
    if uom=='standard atmosphere per metre': return 'P83'
    if uom=='technical atmosphere per metre': return 'P84'
    if uom=='torr per metre': return 'P85'
    if uom=='psi per inch': return 'P86'
    if uom=='cubic metre per second square metre': return 'P87'
    if uom=='rhe': return 'P88'
    if uom=='pound-force foot per inch': return 'P89'
    if uom=='pound-force inch per inch': return 'P90'
    if uom=='perm (0 ºC)': return 'P91'
    if uom=='perm (23 ºC)': return 'P92'
    if uom=='byte per second': return 'P93'
    if uom=='kilobyte per second': return 'P94'
    if uom=='megabyte per second': return 'P95'
    if uom=='reciprocal volt': return 'P96'
    if uom=='reciprocal radian': return 'P97'
    if uom=='pascal to the power sum of stoichiometric numbers': return 'P98'
    if uom=='mole per cubiv metre to the power sum of stoichiometric numbers': return 'P99'
    if uom=='pascal': return 'PAL'
    if uom=='pad': return 'PD'
    if uom=='proof litre': return 'PFL'
    if uom=='proof gallon': return 'PGL'
    if uom=='pitch': return 'PI'
    if uom=='degree Plato': return 'PLA'
    if uom=='pound per inch of length': return 'PO'
    if uom=='page per inch': return 'PQ'
    if uom=='pair': return 'PR'
    if uom=='pound-force per square inch': return 'PS'
    if uom=='dry pint (US)': return 'PTD'
    if uom=='pint (UK)': return 'PTI'
    if uom=='liquid pint (US)': return 'PTL'
    if uom=='portion': return 'PTN'
    if uom=='joule per tesla': return 'Q10'
    if uom=='erlang': return 'Q11'
    if uom=='octet': return 'Q12'
    if uom=='octet per second': return 'Q13'
    if uom=='shannon': return 'Q14'
    if uom=='hartley': return 'Q15'
    if uom=='natural unit of information': return 'Q16'
    if uom=='shannon per second': return 'Q17'
    if uom=='hartley per second': return 'Q18'
    if uom=='natural unit of information per second': return 'Q19'
    if uom=='second per kilogramm': return 'Q20'
    if uom=='watt square metre': return 'Q21'
    if uom=='second per radian cubic metre': return 'Q22'
    if uom=='weber to the power minus one': return 'Q23'
    if uom=='reciprocal inch': return 'Q24'
    if uom=='dioptre': return 'Q25'
    if uom=='one per one': return 'Q26'
    if uom=='newton metre per metre': return 'Q27'
    if uom=='kilogram per square metre pascal second': return 'Q28'
    if uom=='microgram per hectogram': return 'Q29'
    if uom=='pH (potential of Hydrogen)': return 'Q30'
    if uom=='kilojoule per gram': return 'Q31'
    if uom=='femtolitre': return 'Q32'
    if uom=='picolitre': return 'Q33'
    if uom=='nanolitre': return 'Q34'
    if uom=='megawatts per minute': return 'Q35'
    if uom=='square metre per cubic metre': return 'Q36'
    if uom=='Standard cubic metre per day': return 'Q37'
    if uom=='Standard cubic metre per hour': return 'Q38'
    if uom=='Normalized cubic metre per day': return 'Q39'
    if uom=='Normalized cubic metre per hour': return 'Q40'
    if uom=='Joule per normalised cubic metre': return 'Q41'
    if uom=='Joule per standard cubic metre': return 'Q42'
    if uom=='meal': return 'Q3'
    if uom=='page - facsimile': return 'QA'
    if uom=='quarter (of a year)': return 'QAN'
    if uom=='page - hardcopy': return 'QB'
    if uom=='quire': return 'QR'
    if uom=='dry quart (US)': return 'QTD'
    if uom=='quart (UK)': return 'QTI'
    if uom=='liquid quart (US)': return 'QTL'
    if uom=='quarter (UK)': return 'QTR'
    if uom=='pica': return 'R1'
    if uom=='thousand cubic metre': return 'R9'
    if uom=='running or operating hour': return 'RH'
    if uom=='ream': return 'RM'
    if uom=='room': return 'ROM'
    if uom=='pound per ream': return 'RP'
    if uom=='revolutions per minute': return 'RPM'
    if uom=='revolutions per second': return 'RPS'
    if uom=='revenue ton mile': return 'RT'
    if uom=='square foot per second': return 'S3'
    if uom=='square metre per second': return 'S4'
    if uom=='half year (6 months)': return 'SAN'
    if uom=='score': return 'SCO'
    if uom=='scruple': return 'SCR'
    if uom=='second [unit of time]': return 'SEC'
    if uom=='set': return 'SET'
    if uom=='segment': return 'SG'
    if uom=='siemens': return 'SIE'
    if uom=='Standard cubic metre': return 'SM3'
    if uom=='mile (statute mile)': return 'SMI'
    if uom=='square': return 'SQ'
    if uom=='square, roofing': return 'SQR'
    if uom=='strip': return 'SR'
    if uom=='stick': return 'STC'
    if uom=='stone (UK)': return 'STI'
    if uom=='stick, cigarette': return 'STK'
    if uom=='standard litre': return 'STL'
    if uom=='ton (US) or short ton (UK/US)': return 'STN'
    if uom=='straw': return 'STW'
    if uom=='skein': return 'SW'
    if uom=='shipment': return 'SX'
    if uom=='syringe': return 'SYR'
    if uom=='telecommunication line in service': return 'T0'
    if uom=='thousand piece': return 'T3'
    if uom=='kiloampere hour (thousand ampere hour)': return 'TAH'
    if uom=='total acid number': return 'TAN'
    if uom=='thousand square inch': return 'TI'
    if uom=='metric ton, including container': return 'TIC'
    if uom=='metric ton, including inner packaging': return 'TIP'
    if uom=='tonne kilometre': return 'TKM'
    if uom=='kilogram of imported meat, less offal': return 'TMS'
    if uom=='tonne (metric ton)': return 'TNE'
    if uom=='ten pack': return 'TP'
    if uom=='teeth per inch': return 'TPI'
    if uom=='ten pair': return 'TPR'
    if uom=='thousand cubic metre per day': return 'TQD'
    if uom=='trillion (EUR)': return 'TRL'
    if uom=='ten set': return 'TST'
    if uom=='ten thousand sticks': return 'TTS'
    if uom=='treatment': return 'U1'
    if uom=='tablet': return 'U2'
    if uom=='telecommunication line in service average': return 'UB'
    if uom=='telecommunication port': return 'UC'
    if uom=='volt - ampere per kilogram': return 'VA'
    if uom=='volt': return 'VLT'
    if uom=='percent volume': return 'VP'
    if uom=='wet kilo': return 'W2'
    if uom=='watt per kilogram': return 'WA'
    if uom=='wet pound': return 'WB'
    if uom=='cord': return 'WCD'
    if uom=='wet ton': return 'WE'
    if uom=='weber': return 'WEB'
    if uom=='week': return 'WEE'
    if uom=='wine gallon': return 'WG'
    if uom=='watt hour': return 'WHR'
    if uom=='working month': return 'WM'
    if uom=='standard': return 'WSD'
    if uom=='watt': return 'WTT'
    if uom=='Gunter\'s chain': return 'X1'
    if uom=='square yard': return 'YDK'
    if uom=='cubic yard': return 'YDQ'
    if uom=='yard': return 'YRD'
    if uom=='hanging container': return 'Z11'
    if uom=='page': return 'ZP'
    if uom=='mutually defined': return 'ZZ'
    return 'C62'
